apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: git-clone-mvn-
spec:
  taskSpec:
    inputs:
      resources:
      - name: mysources
        type: git
    steps:
    - name: ls1
      image: fedora
      command: ['ls', '/workspace/mysources/java/springboot']
    - name: mvn-build
      image: maven:3.6.0-jdk-11
      command: ['mvn']
      args:
      - -Duser.home=/builder/home
      - clean
      - package
      workingDir:  '/workspace/mysources/java/springboot'      
  inputs:
    resources:
    - name: mysources
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/burrsutter/knative-tutorial-greeter.git
